config/routes.rb
Asino3::Application.routes.draw do
  get "home/index"

  devise_for :users
  
  resources :backups
  
  resources :items do
    resources :notes
    member do 
      get 'add_category'
      post 'toggle_fix'
    end
    collection do 
      get 'get_from_rss'
    end
  end
  
  resources :accounts do
    resources  :items, :rulesets
    member do
      get 'overview'
      get 'course'
    end
    collection do
      get 'search'
      get 'overview'
      get 'course'
    end
  end
  
  resources :categories

  resources :rules
  resources :rulesets

  root :to => "accounts#index"
  

end

app/controllers/home_controller.rb
# Startpage and static pages
class HomeController < ApplicationController
  
  before_filter :load_accounts



end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/help.erb
<div class="column left">
  <h3><%= link_to 'Konten', '/accounts' %></h3>
  <% @accounts.each do |account| %>
    <%= link_to account.title, account, :style => "#{'font-weight:bold;' if account == @account}" %><br/>
  <% end %>

  <h3>Neue Zahlung</h3>
    <%= link_to 'Neue Zahlung', new_account_item_path(@account) if @account %>

  <h3>Kategorien</h3>
  <%= link_to 'Alle Kategorien', categories_path %><br/>
  <%= link_to 'Neue Kategorie', new_category_path(:account_id => @account.id) if @account %>
</div>

<div class="column right">
<h1>Hilfe/FAQ</h1>

<div id="helpify_widget" style="width:600px;"><script src="http://www.helpify.de/widgets/asino/simple.js?search=true&limit=5&css=true"></script></div>

</div>

<div class="clr"> </div>

app/views/home/index.html.erb
<div class="column left" style="width:20%;">
  <% @accounts.each do |account| %>
    <%= link_to account.title, account %><br/>
  <% end %>
</div>

<div class="column right" style="width:70%;">
  <table>
    <%= %>
  </table>
</div>

<div class="clr"> </div>