config/routes.rb
Asino3::Application.routes.draw do
  get "home/index"

  devise_for :users
  
  resources :backups
  
  resources :items do
    resources :notes
    member do 
      get 'add_category'
      post 'toggle_fix'
    end
    collection do 
      get 'get_from_rss'
    end
  end
  
  resources :accounts do
    resources  :items, :rulesets
    member do
      get 'overview'
      get 'course'
    end
    collection do
      get 'search'
      get 'overview'
      get 'course'
    end
  end
  
  resources :categories

  resources :rules
  resources :rulesets

  root :to => "accounts#index"
  

end

app/views/layouts/_flash.erb
<div id="flash" style="display:<%= (self.flash.empty? ? 'none' : 'block') %>;">
  <% if self.flash[:notice] %>
  <div id="flash_notice" class="alert alert-success"><%= self.flash[:notice] %></div>
  <% elsif self.flash[:alert] %>
  <div id="flash_alert" class="alert alert-error"><%= raw self.flash[:alert] %></div>
  <% end %>
</div>

app/views/layouts/_sidebar.erb
<!-- sidebar start -->

  <ul>
      
    <li><%= link_to 'Alle Konten', '/accounts', :class => "#{'active' if !account}" %></li>
    
    <% accounts.each do |acc| %>
      <li><%= link_to acc.title, acc, :class => "#{'active' if acc == account}" %></li>
    <% end %>
    <li><%= link_to 'Neues Konto', new_account_path %></li>
  </ul>
  
  <% unless Account.all.empty? %>
    <ul class="single">
      <li>
        <%= link_to 'Neue Zahlung', 
                    new_account_item_path(account), 
                    :class => "#{'active' if controller.controller_name == 'items' and controller.action_name == 'new'}" if account and account.id %>
      </li>
      <li>
        <%= link_to 'Neue Zahlung', new_item_path              , 
                    :class => "#{'active' if controller.controller_name == 'items' and controller.action_name == 'new'}" if !account %>
      </li>
    </ul>
  <% end %>


<!-- sidebar end -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>asino - Privates Finanzmanagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "rgraph/rgraph"  if @include_graph_scripts %>

    <link href="/favicon.ico" rel="shortcut icon" />
  </head>
  <body data-initializer="<%= controller.controller_name.camelize + controller.action_name.camelize %>">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/"><%= image_tag 'logo_small.png', :size => '96x21' %></a>
          <div class="container nav-collapse">
            <ul class="nav" role="navigation">
              <li class="dropdown">
                <a id="drop1" href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">Konten <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Alle Konten', accounts_path %></li>
                  <% if @accounts %>
                  <% @accounts.each do |acc| %>
                    <li><%= link_to acc.title, acc, :class => "#{'active' if acc == @account}" %></li>
                  <% end %>
                  <% end %>
                  <li><%= link_to 'Neues Konto', new_account_path %></li>
                </ul>
              </li>
              <% if user_signed_in? %>
                <%= li_menu('accounts', 'overview') %>
                  <%= link_to 'Ausgaben', "/accounts/#{@account.id}/overview" if @account %>
                  <%= link_to 'Ausgaben', "/accounts/overview" unless @account %>
                </li>
                <% if Account.count > 0 %>
                <%= li_menu('accounts', 'course') %>
                  <%= link_to 'Verlauf', "/accounts/#{@account.id}/course" if @account %>
                  <%= link_to 'Verlauf', "/accounts/course" unless @account %>
                </li>
                <% end %>
                <%= li_menu 'categories' %>
                  <%= link_to 'Kategorien', categories_path %>
                </li>
                <%= li_menu 'rulesets' %>
                  <%= link_to 'Regeln', rulesets_path %>
                </li>
                <li><%= link_to raw("Sicherung#{' <span class="badge badge-important">!</span>' if current_user.should_backup?}"), "/backups" %></li>
                <li>
                  <%= link_to 'Aktualisieren', "/items/get_from_rss" %>
                </li>
                <li>
                  <%= link_to 'Abmelden', destroy_user_session_path %>
                </li>
              <% else %>
                <li><%= link_to 'Anmelden', new_user_session_path %></li>
                <li><%= link_to 'Registrieren', new_user_registration_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <%= render :partial => 'layouts/flash' %>
      
      <div class="row">
        <div class="span12">
           <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

    <footer>
      <%= link_to 'asino source on github', 'http://github.com/agehret/asino' %>
    </footer>

  </body>
</html>

app/views/layouts/rules.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Rules: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= notice %></p>

<%= yield %>

</body>
</html>