config/routes.rb
Asino3::Application.routes.draw do
  get "home/index"

  devise_for :users
  
  resources :backups
  
  resources :items do
    resources :notes
    member do 
      get 'add_category'
      post 'toggle_fix'
    end
    collection do 
      get 'get_from_rss'
    end
  end
  
  resources :accounts do
    resources  :items, :rulesets
    member do
      get 'overview'
      get 'course'
    end
    collection do
      get 'search'
      get 'overview'
      get 'course'
    end
  end
  
  resources :categories

  resources :rules
  resources :rulesets

  root :to => "accounts#index"
  

end

app/models/account.rb
# encoding: utf-8
# Account actually refers to a real bank account. It holds many items.
class Account < ActiveRecord::Base

  has_many :items, :order => 'created_at desc', :dependent => :destroy
  has_many :rulesets, :dependent => :destroy
  has_many :monthreports, :dependent => :destroy
  
  validates_presence_of :title, :message => "Bitte geben Sie dem Konto einen Namen!"
  validates_uniqueness_of :title, :message => "Dieser Kontoname wird bereits verwendet!"
  validates_inclusion_of :importer, in: AccountImporter::TYPES
  
  # HACK: reusing Saldomat's config field to store the outbank file name, as well.
  # when adding HBCI, change this to use store to store all config settings. it's the most flexible
  # way to store different attributes in an AR (see store docs here:
  # http://apidock.com/rails/ActiveRecord/Store) 
  def outbank_file_name
    self.feed
  end
  
  def import
    AccountImporter.import(self)
  end
end

app/controllers/accounts_controller.rb
# Mangages account specific actions. An account actually refers to a bank account.
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.xml
  
  before_filter :get_accounts, :check_login
  before_filter :load_account, :only => [:show, :edit, :update, :destroy, :overview, :course]
  
  
  def index
    render :action => 'no_accounts' and return if @accounts.empty?
    
    @enddate = (Time.now + @month.to_i.months).at_end_of_month
    @startdate = @enddate.at_beginning_of_month
    @lastmonth = (Time.now.at_end_of_month == @enddate) ? Time.now - 1.month :  @enddate - 1.month

    @sum = Item.until_date(@enddate).sum(:amount)
                           
    @items = Item.for_date(@enddate)
    @income = Item.income.for_date(@enddate).sum(:amount)
    @expenses = Item.expenses.for_date(@enddate).sum(:amount)
    
    sort_items #sort items according to order param
    
    @last_month_income = Item.income.for_current_date(@lastmonth).sum(:amount)    
    @last_month_expenses = Item.expenses.for_current_date(@lastmonth).sum(:amount)

    render :action => 'show'
  end



  def show
    @enddate = (Time.now + @month.to_i.months).at_end_of_month
    @startdate = @enddate.at_beginning_of_month
    @lastmonth = (Time.now.at_end_of_month == @enddate) ? Time.now - 1.month :  @enddate - 1.month
    
    @items = Item.for_account(@account.id).for_date(@enddate)
    if @account
       @sum = Item.for_account(@account.id).until_date(@enddate).sum(:amount) 
    else
      @sum = Item.until_date(@enddate).sum(:amount)
    end
    @income = Item.income.for_account(@account.id).for_date(@enddate).sum(:amount)
    @expenses = Item.expenses.for_account(@account.id).for_date(@enddate).sum(:amount)
    
    @last_month_income = Item.income.for_account(@account.id).for_current_date(@lastmonth).sum(:amount)    
    @last_month_expenses = Item.expenses.for_account(@account.id).for_current_date(@lastmonth).sum(:amount)
    
    sort_items #sort items according to order param
  end
  
  
  # show graph of monthly saldo, expenses, income development
  def course
    @include_graph_scripts = true
    Account.all.each do |account|
      Monthreport.find_or_create(account, Time.now)
    end
    
    if !@account
      @items = Item.without_transfers
      @expenses = Monthreport.grouped_by_date.collect{|m| [m.date, Monthreport.for_date(m.date).sum(:expenses)] }
      @income =   Monthreport.grouped_by_date.collect{|m| [m.date, Monthreport.for_date(m.date).sum(:income  )] }
      @saldo =    Monthreport.grouped_by_date.collect{|m| [m.date, Monthreport.for_date(m.date).sum(:saldo   )] }
    else
      @items = Item.for_account(@account.id).without_transfers
      @expenses = Monthreport.grouped_by_date.collect{|m| [m.date, Monthreport.for_account(@account.id).for_date(m.date).sum(:expenses)] }
      @income =   Monthreport.grouped_by_date.collect{|m| [m.date, Monthreport.for_account(@account.id).for_date(m.date).sum(:income )] }
      @saldo =    Monthreport.grouped_by_date.collect{|m| [m.date, Monthreport.for_account(@account.id).for_date(m.date).sum(:saldo  )] }
    end
  end
  
  
  def overview
    @include_graph_scripts = true

    @enddate = (Time.now + @month.to_i.months).at_end_of_month
    @startdate = @enddate.at_beginning_of_month
    @lastmonth = (Time.now.at_end_of_month == @enddate) ? Time.now - 1.month :  @enddate - 1.month

    if @account 
      @items = Item.for_account(@account.id).for_date(@enddate).without_transfers
      @sum = Item.for_account(@account.id).sum(:amount)
      @income = Item.income.for_account(@account.id).for_date(@enddate).without_transfers.sum(:amount)
      @expenses = Item.expenses.for_account(@account.id).for_date(@enddate).without_transfers.sum(:amount)
    else
      @items = Item.for_date(@enddate).without_transfers
      @sum = Item.sum(:amount)
      @income = Item.income.for_date(@enddate).without_transfers.sum(:amount)
      @expenses = Item.expenses.for_date(@enddate).without_transfers.sum(:amount)
    end

    @expense_categories = categorized_items(@items, 'expenses', @expenses, @lastmonth)
    @income_categories  = categorized_items(@items, 'income', @income, @lastmonth)
  end 
  
  def search
    @sum = Item.sum(:amount)
    
    unless params[:account_id].blank?
      @items = Item.for_account(params[:account_id]).find(:all, 
                  :conditions => ["description LIKE ? or payee LIKE ?", "%#{params[:term]}%","%#{params[:term]}%"], 
                  :order => 'created_at desc')
      @result_saldo = Item.for_account(params[:account_id]).find(:all, 
                  :conditions => ["description LIKE ? or payee LIKE ?", "%#{params[:term]}%","%#{params[:term]}%"]).sum(&:amount) #todo not nice!
    else
      @items = Item.find(:all, 
                  :conditions => ["description LIKE ? or payee LIKE ?", "%#{params[:term]}%","%#{params[:term]}%"], 
                  :order => 'created_at desc')
      @result_saldo = Item.find(:all, 
                  :conditions => ["description LIKE ? or payee LIKE ?", "%#{params[:term]}%","%#{params[:term]}%"]).sum(&:amount) #todo not nice!
    end
    
    render :template => 'accounts/show'
  end
  
  
  def new
    @account = Account.new
  end


  def edit

  end


  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to(@account, :notice => 'Konto wurde erfolgreich angelegt.') }
        format.xml  { render :xml => @account, :status => :created, :location => @account }
      else
        format.html { 
                      flash[:alert] = 'Konto wurde nicht angelegt!'
                      render :action => 'new'
                     }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to(@account, :notice => 'Die Kontodaten wurden erfolgreich ge&auml;ndert.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end


  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to '/', :notice => 'Das Konto wurde gel&ouml;scht.' }
      format.xml  { head :ok }
    end
  end
  
  
  protected
  
  
  # retrieve all accounts, they are needed for the sidebar display
  def get_accounts
    @accounts = Account.all
  end
  
  
  # sort items according to sort params in url
  def sort_items
    @items = @items.sort_by(&:created_at) if params[:order] == 'date'
    @items = @items.sort_by(&:created_at).reverse if params[:order] == 'date desc'
    @items = @items.sort_by(&:payee) if params[:order] == 'payee'
    @items = @items.sort_by(&:payee).reverse if params[:order] == 'payee desc'
    @items = @items.sort_by(&:description) if params[:order] == 'descr'
    @items = @items.sort_by(&:description).reverse if params[:order] == 'descr desc'
    @items = @items.sort_by(&:amount) if params[:order] == 'saldo'
    @items = @items.sort_by(&:amount).reverse if params[:order] == 'saldo desc'
    @items = @items.sort_by(&:category_id) if params[:order] == 'cat'
    @items = @items.sort_by(&:category_id).reverse if params[:order] == 'cat desc'
  end
  
  private

  def load_account
    @account = Account.find(params[:id]) if params[:id]
  end
end

app/views/accounts/course.erb
<div>
  <h1>Verlauf</h1>

  <canvas id="courseGraph" width="800" height="350">[Ihr Internetbrowser unterstützt kein Canvas Objekt.]</canvas>

  <script>
      window.onload = function ()
      {
          var l = new RGraph.Line('courseGraph', [<%= raw @expenses.collect {|m| m[1] * -1}.join(',') %>], 
                                                 [<%= raw @income.collect {|m| m[1]}.join(',') %>],
                                                 [<%= raw @saldo.collect {|m| m[1]}.join(',') %>]);
          l.Set('chart.labels', ['<%= raw @expenses.collect {|d| l(d[0], :format => :monthname_abbrev)}.join("','") %>']);
          l.Set('chart.gutter.left', 70);
          l.Set('chart.outofbounds', true); 
          <% unless @saldo.collect {|m| m[1]}.select {|v| v < 0}.empty? %>
            //l.Set('chart.xaxispos', 'center');
          <% end %>
          l.Set('chart.linewidth', 1.5)
          l.Set('chart.shadow', true);
          l.Set('chart.shadow.offsetx', 5);
          l.Set('chart.shadow.offsety', 5);
          l.Set('chart.shadow.blur', 5);
          l.Set('chart.shadow.color', 'rgba(0,0,0,0.1)');
          l.Set('chart.tickmarks', 'circle');
          l.Set('chart.axis.color', '#777')
          l.Set('chart.spline', !RGraph.isOld());
          l.Set('chart.background', '#fafafa');
          l.Set('chart.background.grid.autofit', true)
          l.Set('chart.background.grid.color', '#eee')
          l.Set('chart.background.grid.autofit.numhlines', 10)
          l.Set('chart.background.grid.autofit.numvlines', <%= @expenses.size - 1 %>)
          l.Set('chart.xticks', <%= @expenses.size - 1 %>)
          l.Set('chart.text.size', 8)
          l.Set('chart.text.color', '#999')
          l.Set('chart.colors', ['#ff9900', '#74cb02', '#888']);
          l.Set('chart.key', ['Ausgaben', 'Einnahmen', 'Kontostand']);
          l.Set('chart.key.position','gutter'),
          l.Set('chart.key.background', 'white');
          l.Set('chart.key.shadow', true);
          l.Set('chart.key.shadow.offsetx', 0);
          l.Set('chart.key.shadow.offsety', 0);
          l.Set('chart.key.shadow.blur', 15);
          l.Set('chart.key.shadow.color', '#ccc');
          l.Set('chart.key.rounded', true);
          l.Set('chart.tooltips', ['<%= raw @expenses.collect {|m| m[1]}.join("','")  %>'],
                                  ['<%= raw @income.collect {|m| m[1]}.join("','")  %>'],
                                  ['<%= raw @saldo.collect {|m| m[1]}.join("','")  %>']);
  
          l.Draw();
      }
  </script>
  <br/>
  Durchschnitt Ausgaben: - <%= currency (@expenses.collect {|m| m[1] * -1}.sum(:amount) / @expenses.size) %><br/>
  Durchschnitt Einnahmen: + <%= currency (@income.collect {|m| m[1]}.sum(:amount) / @income.size) %>
</div>

<div class="clr"></div>

app/views/accounts/edit.html.erb
<h1>Konto bearbeiten</h1>

<%= form_for(@account) do |f| %>
  <%= error_messages_for @account %>

  <p>
    <%= f.label :title, 'Name des Kontos' %><br />
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :importer, 'Quelle' %><br />
    <%= f.select('importer', options_for_select(AccountImporter::TYPES.map { |i| [i, i] }, @account.importer)) %><br />
  </p>
  
  <p>
    <%= f.label :feed, 'Lokale Saldomat RSS-Feed URL' %><br />
    <%= f.text_field :feed %>
  </p>
  <p>
    <%= f.submit 'Speichern' %> oder <%= link_to_function 'abbrechen', 'history.back(-1)' %>
  </p>
<% end %>

<div class="action">
	<%= link_to 'Konto löschen', account_path(@account.id), :method => :delete, :confirm => 'Das Konto mit allen Umsätzen wir gelöscht. Sind Sie sicher?' %>
</div>

app/views/accounts/index.html.erb
<h1>Listing accounts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Feed</th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td><%=h account.title %></td>
    <td><%=h account.feed %></td>
    <td><%= link_to 'Show', account %></td>
    <td><%= link_to 'Edit', edit_account_path(account) %></td>
    <td><%= link_to 'Destroy', account, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New account', new_account_path %>

app/views/accounts/new.html.erb
<h1>Neues Konto anlegen</h1>

<div class="alert alert-block">
asino greift Ihre Kontotransaktionen vom Saldomat RSS Feed ab. Werfen Sie bitte einen Blick in die Saldomat Einstellungen -> "RSS Server um" diesen zu aktivieren.
</div>

<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">  
      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title, 'Name des Kontos' %>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :importer, 'Quelle' %><br />
    <%= f.select('importer', options_for_select(AccountImporter::TYPES.map { |i| [i, i] }, 'Saldomat')) %><br />
  </p>
  
  <p>
    <%= f.label :feed, 'Lokale Saldomat RSS-Feed URL' %><br />
    <%= f.text_field :feed %>
  </p>

  <p class="m20">
    <%= f.submit 'Speichern', :class => 'btn btn-primary' %> oder <%= link_to_function 'abbrechen', 'history.back(-1)' %>
  </p>
<% end %>

app/views/accounts/no_accounts.erb
<%= render :partial => 'layouts/sidebar', :locals => {:account => @account, :accounts => @accounts} %>

<div class="column right">
  <h1>Willkommen zu asino - Management privater Finanzen!</h1>
  <%= raw note 'Willkommen!', 'asino ist noch leer.<br/>Bitte legen Sie zu allererst ein Konto an!' %>
  Sie haben noch keine Konten angelegt.
  <div class="m20">
	<%= link_to 'Neues Konto anlegen', new_account_path, :class => 'button' %>
  </div>
</div>

<div class="clr"> </div>

app/views/accounts/overview.erb
  <h1>
  	<%= link_to image_tag('icons/left.png'), "#{request.path}?month=#{@month - 1}", 
  	                                          :title => l((@startdate - 1.month), 
                                              :format => :monthname) %>

	  Ausgaben <%= @account.title if @account %>: <%= l @startdate, :format => :monthname_and_year %>

  	<%= link_to image_tag('icons/right.png'), "#{request.path}?month=#{@month + 1}", 
  	                                           :title => l((@startdate + 1.month), 
                                               :format => :monthname) %>
  </h1>

  <canvas id="expenseGraph" width="390" height="300">
      [Ihr Internetbroswer unterstützt kein Canvas Objekt.]
  </canvas>
  <script>
      function drawExpenses()
      {
          var p = new RGraph.Pie('expenseGraph', [<%= @expense_categories.collect {|m| m.sum * -1}.join(',') %>]);
          p.Set('chart.title', 'Ausgaben')
          p.Set('chart.title.size', 12)
          p.Set('chart.labels', ['<%= raw @expense_categories.collect {|d| "#{d.percent.round}% #{d.name}" if d.percent > 5}.join('\',\'') %>']);
          p.Set('chart.gutter.left', 120)
          p.Set('chart.gutter.right', 120)
          p.Set('chart.gutter.top', 30)
          p.Set('chart.gutter.bottom', 30)
          p.Set('chart.linewidth', 1);
          p.Set('chart.stroke', '#fff');
          p.Set('chart.strokestyle', '#fff');
          p.Set('chart.labels.sticks', true);
          p.Set('chart.text.size', 7);
          p.Set('chart.text.color', '#888')
          p.Set('chart.align', 'left')
          p.Set('chart.colors', ['#ff9900','#ff9f0e','#ffa51d',
								'#ffab2b','#ffb13a','#ffb649',
								'#ffbc57','#ffc266','#ffc875',
								'#ffce83','#ffd492','#ffd9a0',
								'#ffdfaf','#ffe5be']);
          
          p.Draw();
      }
  </script>
  
  <canvas id="incomeGraph" width="390" height="300">
      [Ihr Internetbroswer unterstützt kein Canvas Objekt.]
  </canvas>
  
  <script>
      function drawIncome()
      {
  
  
          var i = new RGraph.Pie('incomeGraph', [<%= @income_categories.collect {|m| m.sum * -1}.join(',') %>]);
          i.Set('chart.title', 'Einnahmen')
          i.Set('chart.title.size', 12)
          i.Set('chart.labels', ['<%= raw @income_categories.collect {|d| "#{d.percent.round}% #{d.name}" if d.percent > 5}.join("','") %>']);
          i.Set('chart.gutter.left', 120)
          i.Set('chart.gutter.right', 120)
          i.Set('chart.gutter.top', 30)
          i.Set('chart.gutter.bottom', 30)
          i.Set('chart.linewidth', 1);
          i.Set('chart.stroke', '#fff');
          i.Set('chart.strokestyle', '#fff');
          i.Set('chart.labels.sticks', true);
          i.Set('chart.text.size', 7);
          i.Set('chart.text.color', '#888')
          i.Set('chart.align', 'left')
          i.Set('chart.colors', ['#3a6601','#498001','#579902','#66b302','#74cb02','#83e502']);
          
          i.Draw();
      }
      
      window.onload = drawExpenses(), drawIncome()
  </script>
  
  <div class="m20"></div>
  
  <table class="table" style="float:left;width:400px;display:block;">
    <tr>
	  <td class="text-right em" colspan="3">
	    <strong>Ausgaben: <%= currency @expenses.to_i.to_s, 0 %></strong><br/>
	    <hr/>
	  </td>
	  <td class="text-right medium">Unterschied zum Vormonat</td>
	  <td class="text-right"></td>
	</tr>
    <%= render :partial => 'categories/categorized_items', :locals => {:categories => @expense_categories, 
                                                                       :container => 'expenses'} %>
  </table>

  <table class="table" style="float:left;width:400px;display:block;">
    <tr>
	  <td class="text-right em" colspan="3">
	    <strong>Einnahmen: + <%= currency @income, 0 %></strong><br/>
	    <hr/>
	  </td>
	  <td class="text-right medium">Unterschied zum Vormonat</td>
	  <td class="text-right"></td>
	</tr>
    <%= render :partial => 'categories/categorized_items', :locals => {:categories => @income_categories, 
                                                                       :container => 'income'} %>
    <tr>
	  <td class="text-right em" colspan="3">
	    <hr class="nomargin" /><hr class="nomargin" />
	    <strong>Gesamt: <%= currency @income + @expenses, 0 %></strong><br/>
	  </td>
	  <td></td>
	</tr>  
  </table>

  <div style="clear:both"></div>
  <div class="m20 muted"><small>Bitte beachten: Alle Werte in dieser Ansicht sind auf ganze Zahlen gerundet.</small></div>
 

app/views/accounts/show.html.erb
<table class="table table-nohover">
  <tr>
  <td class="al em" colspan="3" rowspan="2">
      <h1 id="pagetitle">
          <% if @startdate %>
          <%= link_to image_tag('icons/left.png'), "#{request.path}?month=#{@month - 1}", 
                              :title => l((@startdate - 1.month), :format => :monthname) %> 
            <%= @account ? @account.title : 'Alle Konten'  %>: <%= l @startdate, :format => :monthname_and_year %>
          <%= link_to image_tag('icons/right.png'), "#{request.path}?month=#{@month + 1}", 
                              :title => l((@startdate + 1.month), :format => :monthname) %>
          <% end %>
          </h1>
    <div style="padding:10px 0px 5px 0px;display:block;">
      <%= form_tag(search_accounts_path, :method => :get, :class => "form-search") do |f| %>
        <div class="input-append">
          <input type="search" name="term" size="20" class="span2 search-query">
          <input type="hidden" name="account_id" value="<%= @account.id if @account %>">
          <%= submit_tag 'Suche', :class => 'btn' %>
        </div>
      <% end %>
      <% if @account %>
        <%= link_to 'Neue Zahlung', new_account_item_path(@account), :class => 'btn' %>
      <% else %>
        <%= link_to 'Neue Zahlung', new_item_path(), :class => 'btn' %>
      <% end %>
    </div>
  </td>
      <td colspan="2" class="text-right"><b>Kontostand: <%= currency @sum %></b></td>
      <td colspan="3"></td>
  </tr>
  <tr>
      <td class="text-right" colspan="2">
        <% if @income %>
          &nbsp;<br/>
            Einnahmen: 
              <span id="income">+<%= currency @income %></span><br/>
          Ausgaben: 
            <span id="expenses"><%= currency @expenses %></span><br/>
          <% end %>
          <% if @income and @expenses %>
            <hr/>
            Gesamt 
            <span id="saldo"><%= currency(@income + @expenses) %></span>
          <% elsif @result_saldo %>
            <hr/>
            Gesamt 
            <span id="saldo"><%= currency(@result_saldo) %></span>
          <hr/>
         <% end %>
      </td>
    <td class="al light" colspan="2">
        <% if @lastmonth %>
          Unterschied zum <%= (@lastmonth).strftime("%d.%m.") %><br/>
          <%= "+" if (@income - @last_month_income) > 0 %>
            <%= currency(@income - @last_month_income) %>
          <%= trend_img(@income - @last_month_income) %><br/>
          <%= "+" if (@expenses - @last_month_expenses) > 0 %>
          <%= currency(@expenses - @last_month_expenses) %>
          <%= trend_img(@expenses - @last_month_expenses) %><br/>
          <hr />
          <%= "+" if ((@income + @expenses) - (@last_month_income + @last_month_expenses)) > 0 %>
          <%= currency((@income + @expenses) - (@last_month_income + @last_month_expenses)) %>
          <%= trend_img ((@income + @expenses) - (@last_month_income + @last_month_expenses))%>
          <hr/>
        <% end %>
    </td>
    <td></td>
    </tr>
  </table>



  <table class="table">
    <thead>
      <tr>
        <th class="text-right"><%= sortlink('Datum', 'date') %></th>
        <th class="al"><%= sortlink('Empfänger', 'payee') %></th>
        <th class="al"><%= sortlink('Beschreibung', 'descr') %></th>
        <th class="al"><%= 'Konto' unless @account %></th>
        <th class="text-right"><%= sortlink('Saldo', 'saldo') %></th>
        <th class="al">Kategorie</th>
        <th style="width:60px;"></th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <%= render :partial => 'items/item_row' , :locals => {:item => item, :account => @account }%>
      <% end %>
      <% if @items.empty? %>
      <tr>
        <td colspan="7">
        Für dieses Konto wurden noch keine Zahlungen eingegeben.
        <% if @account %>
          <div class="m20">
            <%= link_to 'Neue Zahlung eingeben', new_account_item_path(@account), :class => 'button' %>
            <% unless @account.feed.blank? %>
              oder <%= link_to 'Zahlungen von Saldomat übernehmen', "/items/get_from_rss", :class => 'button' %>
            <% end %>
          </div>
        <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

<div class="action">
<%= link_to 'Konto bearbeiten', edit_account_path(@account.id) if @account %>
</div>


<!-- add note modal -->
<div id="addNote" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="noteModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="noteModalLabel">Neue Notiz</h3>
  </div>
  <%= form_for(Item.new, :html => {:method => 'post', :remote => true}) do |f| %>
    <div class="modal-body">
      <%= f.text_area :note, :rows => 4, :style => 'width:320px;' %>
    </div>
    <div class="modal-footer">
      <button class="btn btn-primary">Speichern</button>
      oder
      <a data-dismiss="modal" aria-hidden="true">abbrechen</a>
    </div>
  <% end %>
</div>

<!-- show note modal -->
<div id="showNote" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="showNoteModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="showNoteModalLabel">Notiz</h3>
  </div>
    <div class="modal-body">
      
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Schließen</button>
    </div>
</div>